name: release and push to central
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for ossrh
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: 'ossrh'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: "${{ secrets.GPG_KEY }}"
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'

      - name: build artifact
        run: mvn clean package

      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.37
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          version-patch: true
          gpg-enabled: "true"
          gpg-key-id: "${{ secrets.GPG_KEY_ID }}"
          gpg-key: "${{ secrets.GPG_KEY_BASE_64 }}"
          gpg-passphrase: "${{ secrets.GPG_PASSPHRASE }}"
          maven-args: " -P github,gpg -DskipIT -B  "
          maven-servers: '[{"id": "github", "username": "$GITHUB_ACTOR", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/



      - name: Publish to the Maven Central Repository
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SIGN_KEY: "${{ secrets.GPG_KEY }}"
          SIGN_KEY_ID: "${{ secrets.GPG_KEY_ID }}"
          SIGN_KEY_PASS: "${{ secrets.GPG_PASSPHRASE }}"


